#!/bin/bash
#SBATCH -o %j.out
#SBATCH --gres=gpu:8
#SBATCH -p gpu32
#SBATCH --qos=normal
#SBATCH -J sponge
#SBATCH --nodes=1 
#SBATCH -t 10:00:00

#source activate esmfold
python main.py --name ade20k_seperate_class --base configs/train_ade20k_separate_class.yaml --train --gpus 0,1,2,3,4,5,6,7
# python main.py --name fix_prompts --base configs/train_oxford_pets.yaml --train --gpus 0,1,2,3,4,5,6,7