#!/bin/bash
#SBATCH -o %j.out
#SBATCH --gres=gpu:1
#SBATCH -p gpu31
#SBATCH --qos=normal
#SBATCH -J test
#SBATCH --nodes=1
#SBATCH -t 48:00:00
# python ./dataset_creation/format_dataset.py --dataset ./coco --save_root ./images_pairs
python ./dataset_creation/format_dataset.py --dataset coco --save_root image_pairs_all100kdata/