#!/bin/bash
#SBATCH -o %j.out
#SBATCH --gres=gpu:1
#SBATCH -p gpu31
#SBATCH --qos=normal
#SBATCH -J test
#SBATCH --nodes=1 
#SBATCH -t 20:00:00

#source activate esmfold
# python main.py --name ade20k_seperate_class --base configs/train_ade20k_separate_class.yaml --train --gpus 0,1,2,3,4,5,6,7
# python main.py --name four_tasks_depsprompt:image --base configs/train_pets_nyuv2.yaml --train --gpus 0,1,2,3,4,5,6,7

# python main.py --name test_cls --base configs/train_all100kdata.yaml --train --gpus 0,1,2,3,4,5,6,7
# python main.py --name new --base configs/train_coco_det_black.yaml --train --gpus 0,1,2,3,4,5,6,7
# python main.py --name new --base configs/train_coco_det.yaml --train --gpus 0,1,2,3,4,5,6,7
# python main.py --name cls --base configs/train_coco_cls_seg_det.yaml --train --gpus 0,1,2,3,4,5,6,7
# python main.py --name comeon --base configs/train_all100kdata_rephrased.yaml --train --gpus 0,1,2,3,4,5,6,7
python main.py --name voc_ade_3 --base configs/train_test_panotic_seg.yaml --train --gpus 0,1,2,3,4,5,6,7